# Site settings
title: Tvättlappen
description: Få reda på vad symbolerna på din tvättlapp betyder. Kort och gott.
url: 'http://www.tvättlappen.se' # the base hostname & protocol for your site
ascii_url: 'http://www.xn--tvttlappen-r5a.se'

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: :compressed
timezone: UTC
exclude:
  - CNAME
  - Gemfile*
  - README.md
  - LICENSE
defaults:
  - scope:
      path: '' # everything
    values:
      layout: default
